version: "3.4"
services:
  # ---- base & other ----
  base:
    build:
      context: .
      target: base
  base_python:
    build:
      context: .
      target: base_python
  mgmt:
    build:
      context: .
      target: mgmt
  # ---- Baseline ----
  constant_predictors:
    build:
      context: .
      target: constant_predictors
  # ---- ML ----
  sklearn:
    build:
      context: .
      target: sklearn
  xgboost:
    build:
      context: .
      target: xgboost
  ktrain:
    build:
      context: .
      target: ktrain
  # ---- AutoML ----
  autosklearn:
    build:
      context: .
      target: autosklearn
  flaml:
    build:
      context: .
      target: flaml
  gama:
    build:
      context: .
      target: gama
  h2o:
    build:
      context: .
      target: h2o
  tpot:
    build:
      context: .
      target: tpot
  autogluon:
    build:
      context: .
      target: autogluon
  autopytorch:
    build:
      context: .
      target: autopytorch
  # ---- RecSys ----
  surprise:
    build:
      context: .
      target: surprise
  lenskit:
    build:
      context: .
      target: lenskit
  spotlight:
    build:
      context: .
      target: spotlight
  # ---- AutoRecSys ----
  autosurprise:
    build:
      context: .
      target: autosurprise
  autorec:
    build:
      context: .
      target: autorec